### ISSUE TITLE
The impact of validation set selected from test set

### ISSUE THREAD

**Issue by GaoYQ3991** [IBM/matrix-capsules-with-em-routing#5]
Dear Ashley,
    Thanks for your work fixing some common mistakes in other open source implementations. I found that the validation set was selected from the test set according to the proportion of 10%. Does this lead to an inaccurate test result?

@ashleygritzman

**Comment by ashleygritzman** [comment]
In our final results we used the entire test set. Please go ahead and do some experiments if you think there may be any discrepancies. 
 
 
Ashley Gritzman, PhD
Research Scientist
 
                                                                                                
                                                                        Phone:  +27 (0)11 276 9236
                        Mobile:  +27 (0)82 222 2852
                        E-mail: ashley.gritzman@za.ibm.com
                        Profile:  http://ibmurl.hursley.ibm.com/NU58
                         
                         
                                                                                                 
                        IBM Research | South Africa Lab                        47 Juta Street, Braamfontein, 2000                        Johannesburg, South Africa                                                
 
 
 
 
 
 
----- Original message -----From: GaoYQ3991 <notifications@github.com>To: IBM/matrix-capsules-with-em-routing <matrix-capsules-with-em-routing@noreply.github.com>Cc: Ashley Gritzman <ashley.gritzman@za.ibm.com>, Mention <mention@noreply.github.com>Subject: [EXTERNAL] [IBM/matrix-capsules-with-em-routing] The impact of validation set selected from test set (#5)Date: Thu, Nov 14, 2019 11:03 AM 
Dear Ashley,Thanks for your work fixing some common mistakes in other open source implementations. I found that the validation set was selected from the test set according to the proportion of 10%. Does this lead to an inaccurate test result?
@ashleygritzman

**Comment by GaoYQ3991** [comment]
Thanks for your quick response. I will continue to study and experiment.
