### ISSUE TITLE
Try to continue to train from a checkpoint

### ISSUE THREAD

**Issue by LiGuihong** [IBM/matrix-capsules-with-em-routing#8]
Hi guys,

When I try to continue to train the network from a ckpt_dir, I use the flag "_load_dir_" to do that.
**python3 train_val.py  --load_dir=./logs/smallNORB/20200103_/train/checkpoint**
But the code returns: 
"_load_ckpt directory exists but cannot find a valid 
                    checkpoint to resore, consider using the reset flag_"
I have checked the dir and there is some checkpoints from previous training.
Is there some mistakes that I made in this process?

**Comment by ashleygritzman** [comment]
I found a bug, and have made the fix. Please try out the following and let me know if it works now.

`python3 train_val.py --load_dir=./logs/smallNORB/20200103_`

**Comment by LiGuihong** [comment]
> I found a bug, and have made the fix. Please try out the following and let me know if it works now.
> 
> `python3 train_val.py --load_dir=./logs/smallNORB/20200103_`

Thank you for your reply.
I have tried your solution. 
It still report the same bug.
Thank you again.

**Comment by LiGuihong** [comment]
I solved this issue.
The issue is that in the **627th line of train_val.py** .
I modified the **load_dir** in this function to **load_dir+'checkpoint'**:
_ckpt = tf.train.get_checkpoint_state('load_dir+'checkpoint'')_
Thank you!

**Comment by ashleygritzman** [comment]
Great!
